apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
  namespace: lasample
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hpbonfim/gitops:content
