name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Configure Docker credentials
      run: echo "${{ secrets.DOCKERPW }}" | docker login -u ${{ vars.DOCKERUSER }} --password-stdin
      env:
        DOCKER_USER: ${{ vars.DOCKERUSER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERPW }}
    - name: Build & Push Image
      run: |
        cd ./python
        docker image build -t ${{ vars.DOCKERUSER }}/gitops:content .
        docker push ${{ vars.DOCKERUSER }}/gitops:content
